
CXX		= $(FMATCH_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(FMATCH_BUILDDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 -std=c++0x -fopenmp -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -fopenmp -shared

